products:
  - name: Example-product-silver
    title: Example product silver
    description: |
      Silver version of the example product
    quota: 2
    interval: 1
    timeunit: minute
    proxies:
      - echoheaders
  - name: Example-product-gold
    title: Example product gold
    description: |
      Gold version of the example product
    quota: 3
    interval: 1
    timeunit: minute
    proxies:
      - echoheaders
    openapi: swagger.json
